name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)

trigger:
  batch: true
  tags:
    include:
      - 'r*'
  branches:
    exclude:
      - dev

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'any cpu'
  solutionFile: "Octo.Identity.sln"
  Company: "meshmakers GmbH"
  Copyright: "(c) 2022-2023 meshmakers GmbH"
  isRelease: true #${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  MajorVersion: 0
  MinorVersion: 0

stages:
  - stage: Build
    jobs:
      - job: linux
        displayName: Docker build
        pool:
          name: Gerald-Local-Linux
        steps:
          - checkout: self
            clean: true
            submodules: true
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: 'github.com'
              sshPublicKey: '$(SSHPublicKey)'
              sshPassphrase: 'ZdxQpA4-bici9mR'
              sshKeySecureFile: '-----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAAFmFlczI1Ni1nY21Ab3BlbnNzaC5jb20AAAAGYmNyeXB0AA AAGAAAABBB3ghXynZHucHAW6r44zt7AAAAIAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQAB AAACAQDCtcLkZqRM/ZEm28ngvuf0/eiFWzGZt6uIYNdkzcbStyzWzErxKolcIIsWmP3Dc+ 0pCOqWLzgFmjLq4y9qUNSrZXuhmo/3FtPVFVoUlBqJ+qlNC1bKeUFDfD47zA9cR+oaOBQx W0IvCs7VJASaAG//h2buG+kk99Y+CC7DxkBFMm2is/Rjw0Nw/peOu3mCso2HAUMR4F99Qi O/fzERXmj6klLV/BrXY4mQ/LjUmD7geowyjVwq2tUBaA5xsxRd8eQv5oQjnh9qoMzBK8Wm b8/jeatXF2esf+iLxM0o+ZcbMUX+TOAYiXQBeHowRF4h75NN8+sLDLS/qCV2IMSKTTEC7V OUj3RS/toI1bOtFlTlMOF22AcYaGUG0/ACY0qxprDPgvsWZ3ZfAfsg8ujXj2UQiKun0uxE S3tznAM+d3cl3PYUbdywN/yQ099ZYoeCJteROdigGSmYJNR8jEub12YVw/Z0ZTtiduJmg/ Q6DQBNkllpdxWuufAue6yztA89NYDJd3Nv5C4X9Pwe4SaQZirBqtsnbWMLQ0fbxyioFdOb enTz5UhFqQLoi1i5VTBomU+4wcj5fgi4rIVziacqh5XeRs3O9QN7nHztrNhL16etAOcccA LAcJeCxDyA1/sZEhDxvUjt/9V9I2q0CcVeusBpw/eFjfO9XhvKXYcncxqFxQAAB0Dfve4R K2E5J6PGS3jRJ1EUmZf0tMKlMScdSOYJj0Ws/NP9Gz3YbHd1sy3Pt9dR9KeUMQYOE6tpl3 73Zs0f+gJVtgEK3tXzvAMjkMCzkiu9W5uR7wg4QQVV6McLD0ynQ3B1oc5sckoNq6+grVUm foYkYxEwT3KwkzrF1FEP3Sg7B82/wuhE2HBr8S6L0sqihKwZe5vKev58NljSicnqJzV4Ff H6LuWanHi5L7dqXJYo99uiuxdfownz20iQyTzhsGe870iCLlZ6+8qyNbtt6jYNCa6G5yvS xPV1KK3GiEtb+vKiHUPOnZfhfnvSLDeDv68hNfKSxxObLlgBrrL3vE22c+s0fObsECEVSc Qv5BOGrhr5n0FPQCufsmcwQRgG47ShtHivg+kDGh5Y/YL7UM1iYIhgDcDF0+gP2gUFdUj9 UCuyBP0DAjVgc+tSVlq4c9g3AY+olEMs3KMV9iQZDUeZ1fl/HbtekNm7RwXlJbt33Z2fud IFbNJYRsvpZlOzzmcS/jpf+qN89DDyGYIBb9RUUxMVkEPg7M2HB1iX7buFN5Z2eBNbbz/B NuGiC2VtNcWJvlvD5dbZu35lbsHq3YTjHjWfNCWSK48VEtZT2yBpC9030zV6oUQnE7L5cx Z4VcxWtnjY+srDcGcMzv3IkADiLZ+E/TefJrGR3UpURT9nVoF0RkUjBpycwtZIsaWw3/jw a8sUzuZ8jxaT9wDFft+q/nyKgcRq9c/b0crE9e6RMEGjXUW+sSMsb4dUJ5ZiKKWtaQs1gR L0luaiupipxnWj6aJl/0/34FLCY/mWpe1CW7C+XZEJ9qbAfVcWXMjy9lyCJ3kJtjyDshIb LBKrTGNKfbKQ/+GL+gJej0HGB8ILqJOp89UF7ACX5XYqCvcFrfqJVjvuWxYUlW+VZLvWUg kZv9DBxhdlL7gEXOVaJCaVoP2ApIHz38UG+Zi7/UuEzaOULTqjaP7pzGBNjQKoqLMzhRh8 16hWJVqfj+wQw1jINppEvCsJlhva0moNQAz0gfZJKEeXUXeoC016r3rIbLsSjCnoe25Cfh TWbYjEzj3Ut+kpecmz7NW7IwdFXVfp3D+DA860W7ca6xPjTyXiDaS8JNXOqTBHejsFd4Zz hp1GWaLdxZTz6dH1zJiqPsKM3YM44NLOJLO5m1PohGABRZreJcZxwkqDP3o6559KwWBqJj 5MQxh/LA0Kueqcas0Hv454jTt1e05xaTbK9R7DP8vRD4Hg4AcU2EIsMPuyxkQ7OQrNenSM V6eoy+7Sy9TQ7bIkOtf8ecIwNEw9Q8Xb5TYTlViZzBzqcPqFncBZhNWQge3pGIr7/QeEyh xBpinsH8iVIA2WclQlJ9Prnd0q8psokQN2MIgQ4CJOkilSQkvHh2/7rB2a32/LH4+gOY01 D1LNhqfjyI/gYqyD2vDwQPN94wfbpn8L0v826QG5M5zWQs8HdEzh3jVWEDkwAGI79HyHw0 qdJPV/UlpXHgR7pGBrkXImjKWfJYj5+IcxFNTGiMngXnxA3dDa3Afl/pLszZUuHqv77Jft Ht6ngWnvpMA4WUxXd8aKrPTwwmRj5SA/r02x4L9G7x+v8bivg0F3g4rmZ1JfIf5A3iyITw 8rR8hOBf9v0WRDCBlRTpvHlBv+9XoCnELznSZ+YMb4wHtwWQQVG1nDC4gn2yA3siCKe5MF Ho//sW8Kpyk2jv0yKtZ1RsIzRbCu4tGMo1FcyNCuKAypdutpBwFk4KsQKAUlUb/lUCF3sa XgGIYI9Ydnf2uEYsncDdbqB5Xc+q45lCwn091Vbr4yEuXsMNVLZG67ML6K24YtXY063XcC mf4ssNJCnTvVTK1ygsdG8zM7cXfYju2feRuTbAh0oAvlvqpgvf6V1M+uLArXjZvMDcGF/A 7r8gwMCP7jl/OKUrEMwI5a3BwFLruJaL8ghGAgM6HkJxcYPDqxC5Pkc3lbjoArr227xPp4 nvT0PbKNMoi+QHceEXjxFsFwjTcLzV6L/kB5a9Ud86qaOXILy1abqNxPdKzgUUKHm4Dc1Z cFCCXYK5hBgAY2PEbdvDoy0K6bKPbpFo9f0nLVgk1eAh7sxq8mijTmIz0a4yIMrovFZU96 RXuYBvTLxmEhM65sotVgUkVxDd6W/9is50Pl8Q7PN3MzRtzp4vxncG868C0OT18Oinz3pb OF7pVhFObgQoIgWyJiM88jxPuZFZ29edHecO3cCdg+k7rPWc017ub1f7p3oWcYOAF3CvXS p7P4kmdOCNWaT+9t+ozTuFGpP6JRXRUrmiyfh2Cz9wqf+f6h1MTJTqI50Xvwk+U2vAEqG5 +Tws5yLCFd1SN3cUjhWhi8v6aRP+OSRN6eZVOBLif6DSX0ZaH/Moesv3YXZq5Zb+hHXxMI gg4CSov58Q+FEYuFWmQ6tjCmErZGAIoaJKvRpmFFB4SjMJ2Bn9aqP2x0nKFc03L4+72wW8 dKLqcWeGsfkRubUECgcwfFw2WWbMxfRgjXUyYb/Yc= -----END OPENSSH PRIVATE KEY-----'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Source Branch $(Build.SourceBranch)"
                Write-Host "Source Branch Name $(Build.SourceBranchName)"
                $branch = '$(Build.SourceBranch)'
                $branchName = '$(Build.SourceBranchName)'
                if ($branch.StartsWith("refs/tags/r")) {
                  $major = [int]$branchName.Split(".")[0].substring(1)
                  $minor = [int]$branchName.Split(".")[1]
                  $revision = [int]$branchName.Split(".")[2]
                  $buildNumber = "$major.$minor.$revision.0"
                  Write-Host "##vso[task.setvariable variable=MajorVersion;]$major"
                  Write-Host "##vso[task.setvariable variable=MinorVersion;]$minor"
                  Write-Host "Setting build number to $buildNumber"
                  Write-Host "##vso[build.updatebuildnumber]$buildNumber"
                }
            displayName: 'Set build number'
          - template: setversion.yml
          - task: DotNetCoreCLI@2
            displayName: 'Test'
            inputs:
              command: 'test'
              projects: |
                '**/*Tests.csproj'
                !'**/*SystemTests.csproj'
              testRunTitle: 'CI'
          - task: PowerShell@2
            displayName: 'Create versioninfo file'
            inputs:
              targetType: 'inline'
              script: |
                New-Item $(build.artifactstagingdirectory)/versioninfo.txt
                Set-Content $(build.artifactstagingdirectory)/versioninfo.txt $(Build.BuildNumber)
          - template: buildAndPushDockerImage.yml
            parameters:
              ContainerRegistry: 'dockerhub@ianitor'
              Repository: meshmakers/octo-mesh-identity-services
              Dockerfile: src/IdentityServices/Dockerfile
              IsRelease: ${{ variables.isRelease }}
          - template: buildAndPushDockerImage.yml
            parameters:
              ContainerRegistry: 'dockerhub@ianitor'
              Repository: meshmakers/octo-mesh-policy-services
              Dockerfile: src/PolicyServices/Dockerfile
              IsRelease: ${{ variables.isRelease }}
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: local'
            inputs:
              ArtifactName: local
 

