//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meshmakers.Octo.Backend.IdentityServices.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Meshmakers.Octo.Backend.IdentityServices.Resources.IdentityTexts", typeof(IdentityTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Backend_IdentityServices_UserSchema_Swagger_DisplayName {
            get {
                return ResourceManager.GetString("Backend_IdentityServices_UserSchema_Swagger_DisplayName", resourceCulture);
            }
        }
        
        public static string Backend_IdentityServices_Api_FullAccess {
            get {
                return ResourceManager.GetString("Backend_IdentityServices_Api_FullAccess", resourceCulture);
            }
        }
        
        public static string Backend_IdentityServices_Api_ReadOnlyAccess {
            get {
                return ResourceManager.GetString("Backend_IdentityServices_Api_ReadOnlyAccess", resourceCulture);
            }
        }
        
        public static string Backend_Identity_AccessDenied_Body {
            get {
                return ResourceManager.GetString("Backend_Identity_AccessDenied_Body", resourceCulture);
            }
        }
        
        public static string Backend_Identity_AccessDenied_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_AccessDenied_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Claims_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Claims_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Clients_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Clients_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Clients_NoClientsFound {
            get {
                return ResourceManager.GetString("Backend_Identity_Clients_NoClientsFound", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Common_No {
            get {
                return ResourceManager.GetString("Backend_Identity_Common_No", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Common_Yes {
            get {
                return ResourceManager.GetString("Backend_Identity_Common_Yes", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Consent_Allow_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Consent_Allow_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Consent_ApplicationAccess_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Consent_ApplicationAccess_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Consent_Disallow_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Consent_Disallow_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Consent_PersonalInformation_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Consent_PersonalInformation_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Consent_RememberDecision_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Consent_RememberDecision_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Consent_RequestPermission_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Consent_RequestPermission_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Consent_Tile {
            get {
                return ResourceManager.GetString("Backend_Identity_Consent_Tile", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Consent_UncheckGrants_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Consent_UncheckGrants_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_ApiGrants_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_ApiGrants_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_Body {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_Body", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_Created_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_Created_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_Expires_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_Expires_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_IdentityGrants_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_IdentityGrants_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_NoAccessGranted {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_NoAccessGranted", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_RevokeAccess_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_RevokeAccess_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_LoggedOut_LoggedOutMessage {
            get {
                return ResourceManager.GetString("Backend_Identity_LoggedOut_LoggedOutMessage", resourceCulture);
            }
        }
        
        public static string Backend_Identity_LoggedOut_RedirectMessage {
            get {
                return ResourceManager.GetString("Backend_Identity_LoggedOut_RedirectMessage", resourceCulture);
            }
        }
        
        public static string Backend_Identity_LoggedOut_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_LoggedOut_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Cancel_Button {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Cancel_Button", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Error_InvalidClient_Body {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Error_InvalidClient_Body", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Error_InvalidClient_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Error_InvalidClient_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_External {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_External", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_InvalidUserPassword {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_InvalidUserPassword", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Local {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Local", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Login_Button {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Login_Button", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Password_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Password_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_RememberMe_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_RememberMe_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Username_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Username_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Logout_LogoutMessage {
            get {
                return ResourceManager.GetString("Backend_Identity_Logout_LogoutMessage", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Logout_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Logout_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Privacy_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Privacy_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Profile_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Profile_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Profile_Welcome {
            get {
                return ResourceManager.GetString("Backend_Identity_Profile_Welcome", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Properties_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Properties_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_UserSchema_Roles_Description {
            get {
                return ResourceManager.GetString("Backend_Identity_UserSchema_Roles_Description", resourceCulture);
            }
        }
        
        public static string Backend_Identity_UserSchema_Roles_DisplayName {
            get {
                return ResourceManager.GetString("Backend_Identity_UserSchema_Roles_DisplayName", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Capture_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Capture_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_SubHeader {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_SubHeader", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Success_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Success_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Success_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Success_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Success_Message {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Success_Message", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Confirmation_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Confirmation_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Confirmation_Message {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Confirmation_Message", resourceCulture);
            }
        }
        
        public static string Backend_General_Submit_Header {
            get {
                return ResourceManager.GetString("Backend_General_Submit_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_UserInfo_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_UserInfo_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Manage_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Manage_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Profile_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Profile_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Development_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Development_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_API_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_API_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Diagnostics_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Diagnostics_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_ChangePassword_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_ChangePassword_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Grants_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Grants_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_ManageLogIns_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_ManageLogIns_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_DiscoveryDocument_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_DiscoveryDocument_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_DeviceLogin_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_DeviceLogin_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Logout_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Logout_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Login_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Login_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Redirect_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Redirect_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Redirect_Description {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Redirect_Description", resourceCulture);
            }
        }
        
        public static string Backend_General_Error_Label {
            get {
                return ResourceManager.GetString("Backend_General_Error_Label", resourceCulture);
            }
        }
        
        public static string Backend_General_Error_Title {
            get {
                return ResourceManager.GetString("Backend_General_Error_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_UserInfo_FirstName_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_UserInfo_FirstName_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_UserInfo_LastName_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_UserInfo_LastName_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_UserInfo_FailedAttempts_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_UserInfo_FailedAttempts_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_UserInfo_Id_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_UserInfo_Id_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_LogIn_Validation_Username {
            get {
                return ResourceManager.GetString("Backend_Identity_LogIn_Validation_Username", resourceCulture);
            }
        }
        
        public static string Backend_Identity_LogIn_Validation_Password {
            get {
                return ResourceManager.GetString("Backend_Identity_LogIn_Validation_Password", resourceCulture);
            }
        }
        
        public static string Backend_Identity_General_Username_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_General_Username_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_NewPassword_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_NewPassword_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ConfirmNewPassword_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_ConfirmNewPassword_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ChangePassword_Validation_NewPassword_MinMax {
            get {
                return ResourceManager.GetString("Backend_Identity_ChangePassword_Validation_NewPassword_MinMax", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ChangePassword_Validation_NewPassword {
            get {
                return ResourceManager.GetString("Backend_Identity_ChangePassword_Validation_NewPassword", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ChangePassword_Validation_Match {
            get {
                return ResourceManager.GetString("Backend_Identity_ChangePassword_Validation_Match", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Setup_Status_UsersAlreadyConfigured {
            get {
                return ResourceManager.GetString("Backend_Identity_Setup_Status_UsersAlreadyConfigured", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Setup_Status_PasswordComplexity {
            get {
                return ResourceManager.GetString("Backend_Identity_Setup_Status_PasswordComplexity", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_Email_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_Email_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Setup_Create_Button {
            get {
                return ResourceManager.GetString("Backend_Identity_Setup_Create_Button", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Setup_Subtitle {
            get {
                return ResourceManager.GetString("Backend_Identity_Setup_Subtitle", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Setup_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Setup_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_DeviceCaptureUserCode_Validation_UserCode {
            get {
                return ResourceManager.GetString("Backend_Identity_DeviceCaptureUserCode_Validation_UserCode", resourceCulture);
            }
        }
        
        public static string Backend_Identity_UserCode_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_UserCode_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Manage_StatusMessage_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Backend_Identity_Manage_StatusMessage_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Manage_StatusMessage_SetPasswordSuccess {
            get {
                return ResourceManager.GetString("Backend_Identity_Manage_StatusMessage_SetPasswordSuccess", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Manage_StatusMessage_Error {
            get {
                return ResourceManager.GetString("Backend_Identity_Manage_StatusMessage_Error", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Manage_StatusMessage_RemoveLoginSuccess {
            get {
                return ResourceManager.GetString("Backend_Identity_Manage_StatusMessage_RemoveLoginSuccess", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Manage_StatusMessage_AddLoginSuccess {
            get {
                return ResourceManager.GetString("Backend_Identity_Manage_StatusMessage_AddLoginSuccess", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ChangePassword_Validation_CurrentPassword {
            get {
                return ResourceManager.GetString("Backend_Identity_ChangePassword_Validation_CurrentPassword", resourceCulture);
            }
        }
        
        public static string Backend_Identity_CurrentPassword_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_CurrentPassword_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_General_Password_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_General_Password_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Navigation_Diagnostics_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Navigation_Diagnostics_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_DeviceAuthorized_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_DeviceAuthorized_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ManageProfile_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_ManageProfile_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ManageProfile_Subtitle {
            get {
                return ResourceManager.GetString("Backend_Identity_ManageProfile_Subtitle", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Actions_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Actions_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Actions_CreatePassword_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Actions_CreatePassword_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Actions_ChangePassword_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Actions_ChangePassword_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Actions_ManageLogins_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Actions_ManageLogins_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Actions_Grants_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Actions_Grants_Header", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Home_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Home_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Home_Welcome_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Home_Welcome_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Home_Introduction_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Home_Introduction_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Home_QuickAccess_Header {
            get {
                return ResourceManager.GetString("Backend_Identity_Home_QuickAccess_Header", resourceCulture);
            }
        }
        
        public static string Backend_General_Validation_Title {
            get {
                return ResourceManager.GetString("Backend_General_Validation_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Authorize_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Authorize_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Device_Authorize_Subtitle {
            get {
                return ResourceManager.GetString("Backend_Identity_Device_Authorize_Subtitle", resourceCulture);
            }
        }
        
        public static string Backend_Identity_SetPassword_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_SetPassword_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_SetPassword_Subtitle {
            get {
                return ResourceManager.GetString("Backend_Identity_SetPassword_Subtitle", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Grant_Subtitle {
            get {
                return ResourceManager.GetString("Backend_Identity_Grant_Subtitle", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ManageLogins_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_ManageLogins_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ManageLogins_Subtitle {
            get {
                return ResourceManager.GetString("Backend_Identity_ManageLogins_Subtitle", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ChangePassword_SubTitle {
            get {
                return ResourceManager.GetString("Backend_Identity_ChangePassword_SubTitle", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_ChangePassword_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ManageLogins_NoCurrentOrOtherLogins_Message {
            get {
                return ResourceManager.GetString("Backend_Identity_ManageLogins_NoCurrentOrOtherLogins_Message", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ChangePassword_Button_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_ChangePassword_Button_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Setup_Status_PasswordMissing {
            get {
                return ResourceManager.GetString("Backend_Identity_Setup_Status_PasswordMissing", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Forgot_Password_Link {
            get {
                return ResourceManager.GetString("Backend_Identity_Forgot_Password_Link", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Forgot_Password_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_Forgot_Password_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Forgot_Password_Enter_Email {
            get {
                return ResourceManager.GetString("Backend_Identity_Forgot_Password_Enter_Email", resourceCulture);
            }
        }
        
        public static string Backend_General_Submit_Button {
            get {
                return ResourceManager.GetString("Backend_General_Submit_Button", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Email_Verification_Success {
            get {
                return ResourceManager.GetString("Backend_Identity_Email_Verification_Success", resourceCulture);
            }
        }
        
        public static string Backend_General_Title_Success {
            get {
                return ResourceManager.GetString("Backend_General_Title_Success", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Reset_Email_Sent_Successfully {
            get {
                return ResourceManager.GetString("Backend_Identity_Reset_Email_Sent_Successfully", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Msg_You_Can_Login_With_New_Password {
            get {
                return ResourceManager.GetString("Backend_Identity_Msg_You_Can_Login_With_New_Password", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Success_Redirected_Soon_Message {
            get {
                return ResourceManager.GetString("Backend_Identity_Success_Redirected_Soon_Message", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ResetPassword_PasswordComplexity {
            get {
                return ResourceManager.GetString("Backend_Identity_ResetPassword_PasswordComplexity", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ResetPassword_SubTitle {
            get {
                return ResourceManager.GetString("Backend_Identity_ResetPassword_SubTitle", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Backend_Identity_ResetPassword_Title", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ResetPassword_Button_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_ResetPassword_Button_Label", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ConfirmNewPassword_PasswordMismatch {
            get {
                return ResourceManager.GetString("Backend_Identity_ConfirmNewPassword_PasswordMismatch", resourceCulture);
            }
        }
        
        public static string Backend_Identity_ConfirmNewPassword_PasswordRequired {
            get {
                return ResourceManager.GetString("Backend_Identity_ConfirmNewPassword_PasswordRequired", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Login_LdapUser_Label {
            get {
                return ResourceManager.GetString("Backend_Identity_Login_LdapUser_Label", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_DefaultIdentityError {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_DefaultIdentityError", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_DuplicateEmail {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_DuplicateEmail", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_DuplicateUserName {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_DuplicateUserName", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_DuplicateRoleName {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_DuplicateRoleName", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_InvalidUserName {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_InvalidUserName", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_PasswordRequiresDigit", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_PasswordRequiresUpper", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_PasswordRequiresLower {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_PasswordRequiresLower", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_PasswordTooShort {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_PasswordTooShort", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_UserAlreadyInRole", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_UserNotInRole {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_UserNotInRole", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_InvalidEmail {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_InvalidEmail", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_InvalidRoleName {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_InvalidRoleName", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_InvalidToken {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_InvalidToken", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_PasswordMismatch {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_PasswordMismatch", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_ConcurrencyFailure {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_ConcurrencyFailure", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Setup_Status_EMailMissing {
            get {
                return ResourceManager.GetString("Backend_Identity_Setup_Status_EMailMissing", resourceCulture);
            }
        }
        
        public static string Backend_Persistence_Identity_CommonError {
            get {
                return ResourceManager.GetString("Backend_Persistence_Identity_CommonError", resourceCulture);
            }
        }
        
        public static string Backend_Identity_Logout_RootPage {
            get {
                return ResourceManager.GetString("Backend_Identity_Logout_RootPage", resourceCulture);
            }
        }
    }
}
